### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by Jeroendevr** [BobLuursema/Factorio#2]
Hi Bob,

Can you give a more general direction on how to fill the database? I would like to contribute to the project but I need some help. Thanks.

Jeroen

```
import factorio_database as fdb

adding = fdb.Database

adding.__add_product('gear',2, 'Assembling Machine')
```

Is what I tried.

**Comment by BobLuursema** [comment]
The __add_product function takes 5 arguments, you only gave 3 ('gear', 2 and 'Assembling Machine'). In order the function needs:
name (a string)
buildtime (an integer or string, the function turns it into a string anyway)
buildamount (same as above)
machine_type (a string, needs to be a name already in the machine_types table)
ingredients (a list of lists, containing the name and the amount of ingredients)

So for the iron gear it would be:
`adding.__add_product('gear', 0.5, 2, 'Assembling Machine', [['Iron Plate', 2]]`

Sidenote: the function doesn't yet actually execute the query. So that needs to be implemented as well. Should be really straight forward, just check the other functions :-)

**Comment by Jeroendevr** [comment]
Ok so we have an __add_product attribute. The double __ makes clear that this is a invisible object attribute. So I need to create an extra add_product attribute right? What is the purpose of the private attribute within this function?
